"""Tests for app/services/youtube_captions.py — pure-function helpers.

These tests don't hit the network. They verify:
  - VTT parsing (the heart of the module)
  - Timestamp conversion
  - Language priority selection
  - Source ('manual' vs 'auto') detection
  - Edge cases: empty captions, malformed timestamps, language fallbacks

Integration tests for the actual yt-dlp call live in
tests/test_youtube_captions_job.py and use mocks.

Mirrors the test_youtube_api.py pattern — high coverage on the
pure-function surface so the network-bound code only needs a
thin integration test.
"""

import pytest

from app.services.youtube_captions import (
    _pick_language_priority,
    _vtt_timestamp_to_seconds,
    parse_vtt_text,
)


# ─────────────────────────────────────────────────────────────────────────
# _vtt_timestamp_to_seconds
# ─────────────────────────────────────────────────────────────────────────


@pytest.mark.parametrize("ts,expected", [
    ("00:00:00.000", 0.0),
    ("00:00:01.000", 1.0),
    ("00:01:00.000", 60.0),
    ("01:00:00.000", 3600.0),
    ("01:02:03.456", 3723.456),
    ("12:34.567", 754.567),                  # VTT short form (no hours)
    ("00:01:02,500", 62.5),                  # SRT uses comma decimal
    ("00:00:00.001", 0.001),                 # sub-second precision
])
def test_vtt_timestamp_conversion(ts, expected):
    """All 4 timestamp formats VTT/SRT throw at us parse correctly."""
    actual = _vtt_timestamp_to_seconds(ts)
    assert abs(actual - expected) < 0.01


def test_vtt_timestamp_conversion_handles_floating_point_drift():
    """Regression: 0.1 + 0.2 = 0.30000000000000004 in Python. Make sure
    we don't return weird tiny differences in the parsed result."""
    result = _vtt_timestamp_to_seconds("00:00:00.300")
    assert abs(result - 0.3) < 1e-9


# ─────────────────────────────────────────────────────────────────────────
# parse_vtt_text — the heart of the module
# ─────────────────────────────────────────────────────────────────────────


def test_parse_simple_vtt_returns_segments():
    """Single cue, simple text."""
    vtt = """WEBVTT

00:00:00.000 --> 00:00:02.500
Hello world

00:00:02.500 --> 00:00:05.000
This is the second cue
"""
    segments = parse_vtt_text(vtt)
    assert len(segments) == 2
    assert segments[0]["text"] == "Hello world"
    assert segments[0]["start"] == 0.0
    assert segments[0]["end"] == 2.5
    assert segments[1]["text"] == "This is the second cue"


def test_parse_vtt_strips_html_tags():
    """YouTube auto-captions have <c>color</c> tags. Strip them."""
    vtt = """WEBVTT

00:00:00.000 --> 00:00:02.500
<c>Hello</c> <c.color>world</c>
"""
    segments = parse_vtt_text(vtt)
    assert len(segments) == 1
    # The structural tags are gone, but the text remains
    assert segments[0]["text"] == "Hello world"


def test_parse_vtt_collapses_whitespace():
    """Multi-line cue text should become a single line."""
    vtt = """WEBVTT

00:00:00.000 --> 00:00:05.000
This is
a multi-line
cue
"""
    segments = parse_vtt_text(vtt)
    assert len(segments) == 1
    assert segments[0]["text"] == "This is a multi-line cue"


def test_parse_vtt_skips_note_and_style_blocks():
    """YouTube's auto-generated VTTs include NOTE blocks with metadata
    (the speech recognition confidence, speaker ID, etc). Skip them."""
    vtt = """WEBVTT

NOTE This file was generated by YouTube.

NOTE
Confidence: 0.95
Speaker: en-US-A

00:00:00.000 --> 00:00:02.500
Actual caption text

00:00:02.500 --> 00:00:05.000
Another line
"""
    segments = parse_vtt_text(vtt)
    assert len(segments) == 2
    assert all("NOTE" not in seg["text"] for seg in segments)


def test_parse_vtt_handles_cue_identifier_line():
    """VTT allows an optional identifier line before the timestamp."""
    vtt = """WEBVTT

cue-1
00:00:00.000 --> 00:00:02.500
First cue with identifier

cue-2
00:00:02.500 --> 00:00:05.000
Second cue with identifier
"""
    segments = parse_vtt_text(vtt)
    assert len(segments) == 2
    assert segments[0]["text"] == "First cue with identifier"
    assert segments[1]["text"] == "Second cue with identifier"


def test_parse_vtt_skips_empty_cues():
    """An auto-generated caption that's just a newline shouldn't be
    in the segments list."""
    vtt = """WEBVTT

00:00:00.000 --> 00:00:02.500

00:00:02.500 --> 00:00:05.000
Real content
"""
    segments = parse_vtt_text(vtt)
    assert len(segments) == 1
    assert segments[0]["text"] == "Real content"


def test_parse_vtt_handles_malformed_blocks_gracefully():
    """A block with no timestamp shouldn't crash the parser."""
    vtt = """WEBVTT

this is garbage
no timestamp line here

00:00:00.000 --> 00:00:02.500
Real content
"""
    segments = parse_vtt_text(vtt)
    # Garbage block is skipped silently
    assert len(segments) == 1
    assert segments[0]["text"] == "Real content"


def test_parse_vtt_short_form_timestamps():
    """VTT allows 'MM:SS.mmm' (no hours) for short videos."""
    vtt = """WEBVTT

00:00.000 --> 00:02.500
First

00:02.500 --> 00:05.000
Second
"""
    segments = parse_vtt_text(vtt)
    assert len(segments) == 2
    assert segments[0]["start"] == 0.0
    assert segments[0]["end"] == 2.5


def test_parse_vtt_returns_whisper_shaped_dicts():
    """The output shape must match Whisper's, so downstream code is
    agnostic to which path produced the transcript."""
    vtt = """WEBVTT

00:00:00.000 --> 00:00:02.500
Hello
"""
    segments = parse_vtt_text(vtt)
    assert len(segments) == 1
    seg = segments[0]
    # Whisper shape: {start: float, end: float, text: str}
    assert set(seg.keys()) == {"start", "end", "text"}
    assert isinstance(seg["start"], float)
    assert isinstance(seg["end"], float)
    assert isinstance(seg["text"], str)


def test_parse_vtt_empty_input_returns_empty_list():
    """Empty input = no segments (not an error)."""
    assert parse_vtt_text("") == []
    assert parse_vtt_text("WEBVTT\n") == []  # header only


# ─────────────────────────────────────────────────────────────────────────
# _pick_language_priority
# ─────────────────────────────────────────────────────────────────────────


def test_pick_language_prefers_user_locked():
    """When admin locked a language and it's available, that wins."""
    chosen = _pick_language_priority(
        user_locked="zh-Hans",
        available_languages=["en", "zh-Hans", "ja"],
    )
    assert chosen == "zh-Hans"


def test_pick_language_skips_locked_if_unavailable():
    """If admin locked a language but YouTube doesn't have it, fall
    through to the next priority (NOT an error — yt-dlp might still
    find it as auto-generated)."""
    chosen = _pick_language_priority(
        user_locked="fr",  # not in available
        available_languages=["en", "ja"],
    )
    # Falls through to the first available
    assert chosen == "en"


def test_pick_language_prefers_first_available_when_no_lock():
    """No user lock, English is first in available → English wins (was
    the previous behavior; preserved because preferred_languages defaults
    to English so both rules agree)."""
    chosen = _pick_language_priority(
        user_locked=None,
        available_languages=["en", "zh-Hans", "ja"],
    )
    assert chosen == "en"


def test_pick_language_prefers_english_even_if_list_starts_with_other():
    """Regression for Day-13 catalog-curation bug.

    The Rick Astley YouTube submission had
        caption_languages = ["de-DE", "en", "ja", "es-419", "en", "pt-BR"]
    The old picker returned available_languages[0] = "de-DE", so the
    transcript was German. After the fix, preferred_languages=("en",
    "en-US", "en-GB") is checked BEFORE the first-available fallback,
    so English wins even when YouTube returns non-English first.
    """
    chosen = _pick_language_priority(
        user_locked=None,
        available_languages=["de-DE", "en", "ja", "es-419", "en", "pt-BR"],
    )
    assert chosen == "en"


def test_pick_language_prefers_english_variant_as_fallback():
    """No lock, no available list (yt-dlp will figure it out):
    fall back to a preference list, defaulting to English variants."""
    chosen = _pick_language_priority(
        user_locked=None,
        available_languages=[],  # unknown — we'll let yt-dlp pick
    )
    # No available languages means chosen=None; yt-dlp will pick.
    # The function only kicks in the preferred_languages list when
    # available_languages is non-empty AND doesn't contain the user's
    # lock. With empty available list, return None.
    assert chosen is None


def test_pick_language_falls_back_to_preferred_when_available_empty():
    """Edge case: user locked 'fr', not available, no available list.
    Should return None (yt-dlp will pick whatever it has)."""
    chosen = _pick_language_priority(
        user_locked="fr",
        available_languages=[],
    )
    assert chosen is None


def test_pick_language_returns_none_for_unknown_combo():
    """Defensive: malformed inputs → None (let yt-dlp try)."""
    chosen = _pick_language_priority(
        user_locked=None,
        available_languages=None,
    )
    assert chosen is None


# ─────────────────────────────────────────────────────────────────────────
# Real-world YouTube auto-caption sample (from a public video)
# ─────────────────────────────────────────────────────────────────────────


def test_parse_real_youtube_auto_caption_format():
    """Snapshot of a real YouTube auto-generated VTT file.
    Includes NOTE blocks, multiple cues, and inline tags.
    """
    vtt = """WEBVTT
Kind: captions
Language: en

NOTE
Confidence: 0.9453125

NOTE
Confidence: 0.9453
Line: 0
Word: 0
Op: 0

00:00:00.500 --> 00:00:02.500 align:start position:0%
    <c>hello</c><c> and</c><c> welcome</c>

00:00:02.500 --> 00:00:05.000 align:start position:0%
<c>to</c><c> the</c><c> channel</c>
"""
    segments = parse_vtt_text(vtt)
    # Two real cues; the NOTE blocks are skipped
    assert len(segments) == 2
    assert "hello" in segments[0]["text"]
    assert "welcome" in segments[0]["text"]
    assert "channel" in segments[1]["text"]