"""SQLAlchemy models for the pocket sub-app.

PocketSyncLog — audit trail of what got pushed to a phone (deletions etc).
PocketChunk  — server-side cache of fragmented chunks (so re-renders are fast).
PocketProgress — per-(user, video) chunk completion state.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


class PocketSyncLog(Base):
    """Records sync operations for audit / debugging. Append-only."""

    __tablename__ = "pocket_sync_log"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    action: Mapped[str] = mapped_column(String(16), nullable=False)  # "snapshot" | "delete"
    target_type: Mapped[str] = mapped_column(String(16), nullable=False)  # "course"|"section"|"video"
    target_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )


class PocketChunk(Base):
    """A single teachable chunk for a video, generated by the AI tutor.

    Cached server-side so reopening the iOS app is instant. Re-generated
    only when source data changes (new transcript, new summary) or the
    user explicitly re-runs /m/teach/{id}.
    """

    __tablename__ = "pocket_chunks"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    video_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    index: Mapped[int] = mapped_column(Integer, nullable=False)
    start_ts: Mapped[float] = mapped_column(Float, nullable=False)
    end_ts: Mapped[float] = mapped_column(Float, nullable=False)
    duration_label: Mapped[str] = mapped_column(String(8), nullable=False)  # "2min"|"5min"|"25min"
    concept_title: Mapped[str] = mapped_column(String(255), nullable=False)
    teach_text: Mapped[str] = mapped_column(Text, nullable=False)
    check_question: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )


class PocketProgress(Base):
    """Per-(user, video) chunk completion state.

    One row per (user, video, chunk_index). The phone writes here;
    nothing else. Source data is never modified by the pocket sub-app.
    """

    __tablename__ = "pocket_progress"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    video_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)
    completed_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )
