"""SQLAlchemy models for the pocket sub-app.

PocketSyncLog — audit trail of what got pushed to a phone (deletions etc).
PocketChunk  — server-side cache of fragmented chunks (so re-renders are fast).
PocketProgress — per-(user, video) chunk completion state.
"""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


class PocketSyncLog(Base):
    """Records sync operations for audit / debugging. Append-only."""

    __tablename__ = "pocket_sync_log"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    action: Mapped[str] = mapped_column(String(16), nullable=False)  # "snapshot" | "delete"
    target_type: Mapped[str] = mapped_column(String(16), nullable=False)  # "course"|"section"|"video"
    target_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )


class PocketChunk(Base):
    """A single teachable chunk for a video, generated by the AI tutor.

    Cached server-side so reopening the iOS app is instant. Re-generated
    only when source data changes (new transcript, new summary) or the
    user explicitly re-runs /m/teach/{id}.
    """

    __tablename__ = "pocket_chunks"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    video_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    index: Mapped[int] = mapped_column(Integer, nullable=False)
    start_ts: Mapped[float] = mapped_column(Float, nullable=False)
    end_ts: Mapped[float] = mapped_column(Float, nullable=False)
    duration_label: Mapped[str] = mapped_column(String(8), nullable=False)  # "2min"|"5min"|"25min"
    concept_title: Mapped[str] = mapped_column(String(255), nullable=False)
    transcript_quote: Mapped[str] = mapped_column(Text, default="")
    teach_text: Mapped[str] = mapped_column(Text, nullable=False)
    # MVP0.2 followup #3: structured teach_text broken into two
    # sections by the LLM (## From Transcript / ## From Uploaded Files).
    # NULL means legacy row (LLM didn't emit the headings) — the iOS app
    # falls back to a single Text() of teach_text. Populated by the
    # pocket tutor when the LLM follows the new format. Both fields
    # nullable so we don't have to backfill legacy rows.
    teach_text_transcript: Mapped[str | None] = mapped_column(Text, nullable=True)
    teach_text_materials: Mapped[str | None] = mapped_column(Text, nullable=True)
    check_question: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )


class PocketProgress(Base):
    """Per-(user, video) chunk completion state.

    One row per (user, video, chunk_index). The phone writes here;
    nothing else. Source data is never modified by the pocket sub-app.
    """

    __tablename__ = "pocket_progress"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    video_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)
    completed_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )
    # v0.1.3: phone now persists the user's typed answer + favorite state
    # + the most recent AI verdict. All phone-writable, never affects source.
    user_answer: Mapped[str] = mapped_column(Text, default="")
    is_favorite: Mapped[bool] = mapped_column(Boolean, default=False, index=True)
    last_ai_verdict: Mapped[str] = mapped_column(String(16), default="")  # "got_it" | "partial" | "missed"
    last_ai_explanation: Mapped[str] = mapped_column(Text, default="")
    last_ai_graded_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
